import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavSideBar from './components/navSideBar/NavSideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'e-commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex justify-between">
        <div className='w-[70%] sm:w-[83%] lg:w-11/12'>{children}</div>
        <div className=''>
            <NavSideBar />
        </div>
    </div>
      </body>
    </html>
  )
}
